stages:
  - lint
  - deploy

eslint:
  stage:
    lint
  script:
    - npm install
    - node_modules/.bin/gulp lint
  cache:
    key: "node_modules_cache"
    paths:
      - node_modules/
  except:
    - master
    - tags
  tags:
    - shell

test_deploy:
  stage:
    deploy
  script:
    - npm install
    - node_modules/.bin/webpack --config webpack/webpack.test.config.js
  # - rsync -avzP build/ root@test.thorgene.com:/srv/docker/thorgene-mweb-nginx/html/
  cache:
    key: "node_modules_cache"
    paths:
      - node_modules/
  only:
    - /^test.*$/
  tags:
    - shell

prod_deploy:
  stage:
    deploy
  script:
    - npm install
    - node_modules/.bin/webpack --config webpack/webpack.prod.config.js
    # - rsync -avzP --delete dist/ root@thorgene.com:/srv/docker/thorgene-mweb-nginx/html/thorgene-mweb-$CI_BUILD_REF_NAME/
  cache:
    key: "node_modules_cache"
    paths:
      - node_modules/
  only:
    - tags
  tags:
    - shell